### ISSUE TITLE
Missing ip and external_hostname making mh incompatible with multihost that it should replace.

### ISSUE THREAD

**Issue by jakub-vavra-cz** [next-actions/pytest-mh#1]
As a replacement for pytest-multihost the host ip and external_hostname should be implemented and supported.
The expectation that (internal) hostname is resolvable is not true for machines in cloud and even for use with local containers it would be better to be able to define and use ip addresses.
The ssh logic should be to use first ip (if present), then external_hostname (if present) and then hostname.

**Comment by pbrezina** [comment]
Thank you. I implemented it little bit differently and split ssh related options to standalone key.

See: https://github.com/next-actions/pytest-mh/commit/7507489beeeeaf25c08218402c09a4e89c546352
