### ISSUE TITLE
/usr/bin/bash does not exist in my system

### ISSUE THREAD

**Issue by alejandro-colomar** [next-actions/pytest-mh#95]
Cc: @ikerexxe 

Hi @pbrezina !

As discussed in <https://github.com/shadow-maint/shadow/pull/1131#discussion_r1858407030>, I think you should replace calls of `/usr/bin/bash -c` by `/usr/bin/env bash -c` for portability reasons.

`/bin/bash` is also problematic in some systems (MacOS, BSDs).

Cheers,
Alex

**Comment by pbrezina** [comment]
Thank you, https://github.com/next-actions/pytest-mh/pull/96
